logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd'T'HH:mm:ss.SSS}){faint} %clr(%5p) %clr(:){faint} %m%n%wEx"
  level:
    root: WARN
    org.abiri: INFO
    org.abiri.zeromqcli.ZeromqCliApplicationKt: WARN
